name: test trigger events push paths
on:
  push:
    branches:
    - main
    paths:
    - 'lasttest/last-test-1.txt'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: ls -l